version: '2'

services:

  sc-flask:
    volumes:
      - ./server/:/opt/sc/sc-flask
    env_file:
      - server/env/.test.env
    command: bash docker/entrypoint.test.sh

  sc-arangodb:
    env_file:
      - server/env/.test.env
