DOMAIN=pootle.docker

POOTLE_TITLE=SuttaCentral Translation Server
POOTLE_ADMIN_EMAIL=admin@email.foo
POOTLE_ADMIN_PASSWORD=not_set
POOTLE_ADMIN_NAME=admin

POOTLE_DEBUG=False

MAILGUN_ACCESS_KEY=not_set
MAILGUN_SERVER_NAME=not_set

MYSQL_ROOT_PASSWORD=not_set
MYSQL_USER=pootle
MYSQL_PASSWORD=pootle
MYSQL_DATABASE=pootle_db

