name: SuttaCentral CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_COMPOSE_VERSION: 1.15.0

    steps:
      - name: Checkout master repo
        uses: actions/checkout@v2

      - name: Initialize docker
        uses: docker-practice/actions-setup-docker@master
        
      - name: Build  
        run: |
          make prepare-tests
          docker wait sc-frontend
          docker-compose logs
          docker ps

      - name: Test
        run: make test
       
