name: SuttaCentral CI

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_COMPOSE_VERSION: 1.15.0

    steps:
      - name: Checkout master repo
        uses: actions/checkout@v2

      - name: Build
        run: source ./ci/before_install.sh

      - name: Test
        run: source ./ci/test.sh
